### ISSUE TITLE
update by SKU does not work

### ISSUE THREAD

**Issue by stmeissner** [sphereio/sphere-node-product-csv-sync#107]
When using parameter `--matchBy sku` the product import was aborted with the message `'[row 2] Product update not necessary.' ]`

the structure of the CSV file looks like:
productType, sku, name.en, slug.en, ...

**Comment by hajoeichler** [comment]
@stmeissner could you provide also the 2nd row of the CSV file please.

**Comment by stmeissner** [comment]
here is the CSV file:
[sku_I019917_1_import.csv.txt](https://github.com/sphereio/sphere-node-product-csv-sync/files/43726/sku_I019917_1_import.csv.txt)

**Comment by PhilippSpo** [comment]
At the moment, when you provide an SKU the csv-sync only looks at the variant information, so the name of the product won't update in this case for example. What are you expecting to happen? @stmeissner

**Comment by stmeissner** [comment]
@PhilippSpo let's say you change the description in the [ProductData](http://dev.commercetools.com/http-api-projects-products.html#product-data) and you update by SKU, nothing happens.

**Comment by PhilippSpo** [comment]
@stmeissner I just tried this with searchKeywords (which also is productData) and I had to provide SKU and variantId for it to work. Only with SKU it would not work.

**Comment by PhilippSpo** [comment]
@hajoeichler @stmeissner @mmoelli  I think it is a common use case to only have an SKU and not have the corresponding VariantId for the SKU. So we would need to implement that updating by SKU (without variantID) is possible.

**Comment by mmoelli** [comment]
@PhilippSpo I absolutely comply. We recently reworked the update actions that as variant identifier the SKU can be used instead of the variant id. To use this, I think we have to do some work at the sdk which generates the update actions. Nevertheless, one of these params (variantId or SKU) have to be present.

**Comment by PhilippSpo** [comment]
Ok I found something interesting [here](https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/src/coffee/validator.coffee#L56).
If there is a SKU but NO variantId then only the variants get updated, but not the base product attributes. Is this still a valid behaviour? @emmenko @hajoeichler

**Comment by hajoeichler** [comment]
Well it was the first move to allow sku based updates.
You can of course get to the product from the sku and also adjust product level information.

So, it's another feature IMHO

**Comment by PhilippSpo** [comment]
@hajoeichler Agree. It would just be a matter of removing the lines I linked to, right?

**Comment by hajoeichler** [comment]
No, as the important part is how we build the structure we compare. This happens here: https://github.com/sphereio/sphere-node-product-csv-sync/blob/2e96f25f6660a265b5c52e9ce77bf671fe0c5b84/src/coffee/validator.coffee#L136

**Comment by junajan** [comment]
Hello all, I took this issue and tried to remove a condition on the line https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/src/coffee/validator.coffee#L59 as @PhilippSpo suggested but the tests were not working then so I will have to go deeper to find the solution.

**Comment by junajan** [comment]
Hello @hisabimbola, @hajoeichler and @PhilippSpo - please check this PR which allows us to update a product info using only SKU https://github.com/sphereio/sphere-node-product-csv-sync/pull/147

**Comment by junajan** [comment]
I am closing this issue because it was resolved in this PR #147
