### ISSUE TITLE
Provide docker container so it can be easily build and executed on any OS

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-node-product-csv-sync#116]

**Comment by Siilwyn** [comment]
@hisabimbola this was mentioned before maybe we should discuss this. If we go with a container we should do it for all tools though, not just this one.

**Comment by hisabimbola** [comment]
Yeah, I agree.

Maybe something we can start with the monorepo modules.

**Comment by Siilwyn** [comment]
+1
I've 'moved' this issue: https://github.com/commercetools/nodejs/issues/80

**Comment by hisabimbola** [comment]
Since this issue has not been fixed, I do not advice we close it.

We should close this issue only when the other issue have been closed/fixed

Then that will automatically fix/close this also

**Comment by Siilwyn** [comment]
Let's do it only for the monorepo modules.
