### ISSUE TITLE
cell with multiple categoryOrderHints cannot be used for updates

### ISSUE THREAD

**Issue by abernhar** [sphereio/sphere-node-product-csv-sync#118]
If I use multiple categoryOrderHints and connect them using the multi value delimiter, only the first update action is getting created. all following categoryOrderHints will be ignored.

**Comment by PhilippSpo** [comment]
This is a bug in the SDK actually, not a bug in the `sphere-node-product-csv-sync`.
It has been reported in the SDK [here](https://github.com/sphereio/sphere-node-sdk/issues/154).

**Comment by PhilippSpo** [comment]
This is fixed now with the [1.15.3](https://github.com/sphereio/sphere-node-sdk/releases/tag/v1.15.3) release of the SDK
