### ISSUE TITLE
Support export mapping for set of ltext attributes

### ISSUE THREAD

**Issue by mmoelli** [sphereio/sphere-node-product-csv-sync#124]
Hey there,

currently I have a customer who is using a set of ltext attributes. It seems, that import mapping of these kind of attributes is already covered (https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/src/spec/mapping.spec.coffee#L314) but the export mapping is missing here. For localized fields, this seems to be the only case currently missing (https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/src/spec/exportmapping.spec.coffee#L94-L96).

Please also support the attribute mapping of sets of ltext for exports.

Thanks.

**Comment by Siilwyn** [comment]
Work in progress:
https://github.com/sphereio/sphere-node-product-csv-sync/tree/124-export-mapping-ltext

**Comment by Siilwyn** [comment]
#124
