### ISSUE TITLE
.ZIP archive import processing only the first file (the last, actually)

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-node-product-csv-sync#133]
I have no idea why. the temporary extract folder contains all the files.   

I'm even starting it with "--continueOnProblems".    may have to do with #131

**Comment by skyriakou** [comment]
@nkuehn since the bug is more than 2 years old and we did not receive any other issues regarding this,  we assume that it is longer relevant. Is it still relevant?
Thanks.

**Comment by nkuehn** [comment]
What's relevant is your decision and defining that stuff that nobody else asked for in two years are obviously not relevant is OK imho.  
It's not okay though - on a communication level - to just close issues without any hint on the background.

**Comment by skyriakou** [comment]
I agree, in the next clean-up we will include a comment. Thanks:)
