### ISSUE TITLE
Running export command with 'json' option outputs help information

### ISSUE THREAD

**Issue by VasumathiJayakumar** [sphereio/sphere-node-product-csv-sync#139]
Command taken from the readme: `node lib/run.js export --projectKey <project_key> --clientId <client_id> --clientSecret <client_secret> -j out.json`

Running this results in command usage output being shown, from `--help`.

The culprit seems to be the json option.

**Comment by junajan** [comment]
Hello @VasumathiJayakumar - I suppose that this tool - https://github.com/sphereio/sphere-node-cli should handle product export/import in `JSON` format' once it is finished. 

It looks also that the JSON export was never finished so it is a question if we should implement it here or remove this option from csv-sync and wait for its implementation in sphere-node-cli module.

**Comment by junajan** [comment]
Hello @hisabimbola @Siilwyn .. any idea what should we do with this issue?

**Comment by Siilwyn** [comment]
I would say let's remove it for now, we have plenty of technical debt across most tools & adding new features only builds that up.
