### ISSUE TITLE
Duplicate header entries

### ISSUE THREAD

**Issue by junajan** [sphereio/sphere-node-product-csv-sync#143]
When doing a full export, script will now load all productTypes and for every productType it creates a header and export products.

If the productType has a custom attribute with the same name as one of the common attributes (categories, images, taxCategories, ..etc) it will create template with duplicate entries, for example:
`_published,productType,variantId,id,sku,categories,channels,categories`

And the export will fail with an error: `There are duplicate header entries!`

This can happen only for old projects because sphereApi should have attribute.name restriction now which permits user to create attributes with duplicate names.

I created this PR which removes duplicit header entries from generated template so the full export will work but it will skip custom attributes named as the common attributes: https://github.com/sphereio/sphere-node-product-csv-sync/pull/142

**Comment by junajan** [comment]
Updated here https://github.com/sphereio/sphere-node-product-csv-sync/pull/142 currently on hold (this issue can happen only on outdated projects)

**Comment by junajan** [comment]
I am closing this issue because we discovered that this issue can happen only on a really old project which did not have restrictions for attribute names and it should not occur again

**Comment by ValeSauer** [comment]
@junajan One can still create attributes named "productType" via AdminCenter. I did it some weeks ago and ran into this issue. I renamed it and it export worked.

**Comment by hisabimbola** [comment]
@ValeSauer I think this should be reported to the API. It should be avoided from the API level....

**Comment by junajan** [comment]
I agree with Abi - it should be handled on API because there can be other possible issues when there are multiple attributes with the same name.
