### ISSUE TITLE
Publish/Unpublish product when _published value differ from products publish state

### ISSUE THREAD

**Issue by junajan** [sphereio/sphere-node-product-csv-sync#148]
When I export products (for example) with this template:
`_published,productType,variantId,id,sku,name.de`

I get few products, for example:
`false,fliesenkeile-und-kreuze-030001002000,1,3022126d-a690-4737-ac5c-d2d4ec12c5b7,1150214,updated-name3`

Then I change `_published` from `false` to `true` and import it back. Changed product should be published but it is not changed with message `Product update not necessary`.

**Comment by junajan** [comment]
Hello all, this is a summary of our discussion with @Siilwyn about possible solutions.

If someone exports products with `_published` column and change its value from `false` to `true` (or opposite), it is expected to change products state during the import. Currently `_published` column is ignored so we were thinking to put there additional process which would set publish state based on its value.

Another idea was, that columns starting with an underscore are internal and thus should be readonly so we were thinking about new column named `published` which would contain same data as `_published` and the import script would update product state if the value from csv differs from state saved on Sphere.

Questions are:
- if the name `published` can colide with custom product attribute
- if it won't colide with an import parameter `--publish` (we can turn off this post-import process when `--publish` parameter is set)

**Comment by junajan** [comment]
@hajoeichler @PhilippSpo @hisabimbola - can you please look at this idea and tell us what do you think about that?

**Comment by mmoelli** [comment]
@junajan AFAIK the underscore in the beginning of the term indicated that this field cannot be changed through CSV import. It's the same with ```hasStagedChanges``` which is just a status field and cannot be directly set as its calculated based on product information. I would therefore recommend to move from ```_published``` to ```published``` to generate a change for the product. In the export, we could still support both versions, but only when importing without underscore the appropriate changes would be generated.

WDYT?

**Comment by hajoeichler** [comment]
Hey guys. This tool has an extra subcommand to deal with the state changes (un/publish and delete).
Thus I would not touch anything here, but make clear what you mentioned. `_` prefix means read-only.

Can you please adjust the README.

**Comment by Siilwyn** [comment]
Yes we noticed but that command does not use `_published` at all. As in there is no code using it, only exists as a variable that's all.

**Comment by junajan** [comment]
@hajoeichler - also that `status` subcommand is not accessible from impex. It makes sense to have a possibility to select some products which will be published/unpublished during import.

**Comment by junajan** [comment]
@mmoelli - sounds good to me. What others think about this approach?

**Comment by mmoelli** [comment]
@junajan the state command is actually available through impex: https://impex.commercetools.com/commands/product-state

**Comment by junajan** [comment]
ahh, you are right @mmoelli .. my mistake.

**Comment by stmeissner** [comment]
@junajan from my point of view the column `_published` should not be considered at all during import. Therefore no bug, or?

**Comment by junajan** [comment]
@stmeissner I agree - so should we add and use `published` attribute during export/import?

**Comment by stmeissner** [comment]
@junajan what would be useful is a flag that allows me to export only products that have been published.
I tried with query filter `masterData(published=true)` to achieved that, which worked fine.
Then I tried to export only the unpublished products with `masterData(published=false)`, but I got the same result as for `published=true`

How does it work anyways? I guess only the current product projection is exported?

**Comment by hisabimbola** [comment]
@junajan any update on this?

**Comment by junajan** [comment]
@stmeissner - based on this: https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/src/coffee/export.coffee#L127
It uses `productProjections` endpoint so no `masterData` object is needed. Also, it loads by default `staged` product versions:
https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/src/coffee/export.coffee#L161

To export published / not published products you can use these two query strings:
**staged published:** where=published%3Dtrue&staged=true
**current published:** where=published%3Dtrue&staged=false
**not published:** where=published%3Dfalse&staged=true

I suggest to create some examples which can be used as a query string so it will be less confusing.

Also what should I do with this issue? Should we add another `published` column which will trigger publish state change when doing a product import?

**Comment by stmeissner** [comment]
@junajan @hisabimbola since we know have the workaround to achieve this with queries, we can close the issue. It is a matter of documentation, not a lack of features.

**Comment by hisabimbola** [comment]
@junajan that sounds good. We can add a `published` column that triggers publishing the product after importing.

**Comment by hisabimbola** [comment]
@stmeissner the original _issue_ of this issue has not be resolved 😬

**Comment by stmeissner** [comment]
@hisabimbola right 😬 
so it would be two requests for a product having the value for the new column set to `true`: 
* update + publish

Since this flag triggers an action and does not describe the state of the product I would name this column `publish` accordingly (not `published`). WDYT?

**Comment by hisabimbola** [comment]
yeah, I agree @stmeissner 

Cc @junajan
