### ISSUE TITLE
support validity period of Product Price

### ISSUE THREAD

**Issue by stmeissner** [sphereio/sphere-node-product-csv-sync#150]
the fields `validFrom` and `validTo` of [Product Price](https://dev.commercetools.com/http-api-projects-products.html#price) can neither be exported nor imported through this tool.

This information currently get's lost; even worse it leads to invalid prices since you'll get two or more prices with same currency and country for the same variant in the exported CSV file.

Currently each price has following pattern:
`<country>-<currenyCode> <centAmount>|<discountedCentAmount> <customerGroupName>#<channelKey>` that needs to be extended to accommodate additional validity period.

**Comment by junajan** [comment]
@stmeissner @hisabimbola @PhilippSpo - Please check my idea and add your comments before I start working on this.

Here is an export price mapping function:
https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/src/coffee/exportmapping.coffee#L143

And here is a parsing regexp:
https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/src/coffee/constants.coffee#L42

We can add another two special characters which will separate validFrom and validTo dates (saved in ISO 8601 format - eg. `2001-09-11T14:00:00.000Z`).

What about this format?
`<country>-<currenyCode> <centAmount>|<discountedCentAmount> <customerGroupName>#<channelKey>$<validFrom>~<validTo>`

**Comment by hisabimbola** [comment]
I think this is good...

**Comment by hisabimbola** [comment]
Fixed by #151
