### ISSUE TITLE
Export categoryOrderHints by externalId

### ISSUE THREAD

**Issue by floriansattler** [sphereio/sphere-node-product-csv-sync#154]
Currently productExport only supports export of categoryOrderHints by Id. However if customers want to sync there categoryOrderHints between two projects they have to exchange the ids of the projects first as they are unique for each project. It would be easier if there would be a possibility to select if categoryOrderHints should be exported by iD or externalId as externalIds would be the same along the projects.

**Comment by floriansattler** [comment]
Also an import function should be provided which maps the externalId to id

**Comment by junajan** [comment]
Closing because the underlying PR was merged.

**Comment by hisabimbola** [comment]
For next time, this issue should be closed by referencing 👁
