### ISSUE TITLE
Incorrectly shifted rows in export file

### ISSUE THREAD

**Issue by junajan** [sphereio/sphere-node-product-csv-sync#157]
Sometimes the **CSV** file has shifted rows (xlsx export does not have this issue):
<img width="319" alt="screen shot 2017-02-10 at 11 16 00" src="https://cloud.githubusercontent.com/assets/1090382/22823487/36874316-ef84-11e6-8d80-af1b01e8f2cb.png">
<img width="157" alt="screen shot 2017-02-10 at 11 16 14" src="https://cloud.githubusercontent.com/assets/1090382/22823488/3688d988-ef84-11e6-844d-ae4cf378d4a5.png">

Example xlsx file with wrong rows: 
[first 61 rows.xlsx](https://github.com/sphereio/sphere-node-product-csv-sync/files/766386/first.61.rows.xlsx)

(Note: this issue was reported by Thorsten Bayer)

**Comment by hisabimbola** [comment]
@junajan Can you provide more context on this issue??

and how to reproduce it

**Comment by junajan** [comment]
@hisabimbola - I didn't have time for this yet. I will do that once I have time.

**Comment by junajan** [comment]
I tried to reproduce this error and it looks like the problem is somehow connected with a quote (at the end of the first cell on the broken line) but when I tried to reproduce it on some testing projects, everything was working

**Comment by junajan** [comment]
We found out that the problem occurs only in MS Excel and only if the row contains a new line character (even if it is escaped using double quotes).
Example of an invalid row:
```csv
2-n-s,ausstattung-2109-lt-c.de,inhalt-2219-n-c,schnellstop-2261-le-s,max-korngroesse-0560-n-s,max-eintauchtiefe-0548-n-s,kettenspannung-2258-lt-s.de
terrassenhoelzer-und-dielen-024001001006,1,4280079,,,,,,,,,,,,,,,,,,,,,,,,,,,001 BAUSTOFFE                     ,001009 GARTENLANDSCHAFTSBAU          ,"001009009 HOLZFLIESEN, GARTENBAUHÖLZER  ",08 HR HALBACH      ,RETTENMEIER     ,718056,,,,Unterlage für Holz- und Terrassenböden,Vermeidung von Staunässe,Dampfdiffusionsfähig,Trittschalldämmend,Unverrottbar und rutschfest,schwarz,   ,,,,   ,   ,,,,,,10000001267528,na,,,,96045002501,,,,,,1000000228088,3163,,,Gummigranulat,,"Die Auflagepads mit den Maßen 9 x 6 x 0,8 cm werden zur Vermeidung von Staunässe unter Holz- und Terrassenböden verlegt. Dank ihrer widerstandsfähigen Eigenschaften können sie dauerhaft als Unterlage im Außenbereich eingesetzt werden. Achten Sie beim Verlegen darauf, die Pads in regelmäßigen Abständen zu positionieren.
Im Lieferumfang sind 48 Pads enthalten.",,,,20161204031517,0,,PCE,1,n,PCE,1,neu_angelegt,neu_angelegt,,,freigegeben,,,,,,true,,YA,,,,,,,,,,,,,,,,,,,,,,,,,,,9,,6,,,,,,Schwarz
```

**Comment by junajan** [comment]
@hisabimbola @Oehmi - this issue is only in MS Excel which has a problem when importing rows containing break lines. We tried to
- import original file exported from Impex
- then the same file with replaced break lines to \n, \r and \r\n
- then the file (containing break lines) generated from google docs in utf-8 and win1250 encoding

And nothing helped. There was some advice to use xlsx instead of csv which does not have this issue. More info can be seen here: http://stackoverflow.com/questions/2668678/importing-csv-with-line-breaks-in-excel-2007

I propose to close this issue because it is more an issue of MS Excel.

**Comment by hisabimbola** [comment]
Thanks for checking it out @junajan 

You can close the issue.
