### ISSUE TITLE
Wrong link to the latest version in documentation

### ISSUE THREAD

**Issue by junajan** [sphereio/sphere-node-product-csv-sync#158]
On the readme page here https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/README.md we have a link which leads to this address https://github.com/sphereio/sphere-node-product-csv-sync/archive/latest.zip

It should point to the latest version of this module but module on this address has version "0.6.7" instead.

**Comment by Siilwyn** [comment]
Let's remove the 'release as zip' completely.

**Comment by junajan** [comment]
Or we can put there link to this page https://github.com/sphereio/sphere-node-product-csv-sync/releases

**Comment by Siilwyn** [comment]
That's probably not needed, GH releases are well known at this point I think.

**Comment by hisabimbola** [comment]
I will say we reference the releases page on Github else we remove the `Zip` section totally

**Comment by junajan** [comment]
I will replace ZIP section with some info how to install it as a global module.
