### ISSUE TITLE
XLSX reader translates FALSE into "0"

### ISSUE THREAD

**Issue by junajan** [sphereio/sphere-node-product-csv-sync#159]
When importing data from XSLX file, it translates string "FALSE" into "0" which breaks boolean parser with this error: '[row 2:allg-sperrvermerk-2076-b-s] The value \'0\' isn\'t a valid boolean!'

File with this behavior can look for example like this [simple.xlsx](https://github.com/sphereio/sphere-node-product-csv-sync/files/770590/2rows-simple.xlsx)

**Comment by junajan** [comment]
The strange thing is, that it is translating only "FALSE", if there is "TRUE", "true" or "false" it is loaded correctly as a string.

**Comment by junajan** [comment]
The reason for this is, that some tools like msExcel treat some string values as booleans represented by numbers (0 or 1). Therefore we should handle those values when parsing booleans in our code.

**Comment by CT-thorstenbayer** [comment]
keep in mind that this affects the englisch version of excel. TRUE FALSE treated as 0 AND 1.

The german excel does the same for WAHR and FALSCH
