### ISSUE TITLE
exports all product-types, even when a productTypeId is specifically defined

### ISSUE THREAD

**Issue by adnasa** [sphereio/sphere-node-product-csv-sync#171]
### Description

This was discovered via [Impex](https://impex.commercetools.com).
The problem is that even when the where-predicate field has specified a `productTypeId` along with other queries, data from all other productTypes are being exported as well. 

```
variants(attributes(name="attr-enum-sfa" and value(key="enum0"))) and productType(id="4228c68d-123f-43e3-a7b1-14af1ab85b0d")
```

I always assumed that the product-export command uses `productProjections`. 
Testing the same query in `product-projections` of API playground yields an accurate result.

### How to re-produce

1. Go to product-projections of the API-playground
2. Specify a productTypeId in the where-predicate field, and other queries to help narrow down the list
3. Copy the where-predicate and paste into the where predicate field of Impex
4. Export

### Expected Behaviour

Product data of only this productType is being exported (leveraging `where`-predicate)

### Current Behaviour

Product data of all productTypes are being exported

### screenshot

![impex-specified producttypeid 4228c68d-123f-43e3-a7b1-14af1ab85b0d](https://user-images.githubusercontent.com/462507/27188178-ab09d7fa-51ed-11e7-9fb6-311131f5f2ac.png)

### Possible solution

I think this problem has two aspects

1. Either the `sphere-node-sdk` doesn't read the where-predicate properly to pass along to where-predicate of the product-projections endpoint
2. The export command [fetches all productTypes first](https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/src/coffee/export.coffee#L150-L156), which is an unnecessary operation when a productTypeId is already specified in the command

**Comment by wizzy25** [comment]
This is because you're passing the query wrong. You should add `where=` at the beginning:
```bash
where=variants(attributes(name="attr-enum-sfa" and value(key="enum0"))) and productType(id="4228c68d-123f-43e3-a7b1-14af1ab85b0d")
```

**Comment by adnasa** [comment]
are you sure, @wizzy25 ?
![img](https://api.monosnap.com/rpc/file/download?id=5UezIUY4MhcwS8eHcYdGwcXpV66sE8)

**Comment by wizzy25** [comment]
@adnasa That is working correctly.
