### ISSUE TITLE
"Where Predicates" do not work as expected

### ISSUE THREAD

**Issue by VasumathiJayakumar** [sphereio/sphere-node-product-csv-sync#172]
### Description
Export product with "Where predicate" set to 

> masterData(published=false)

### Expected Behavior
All products which has published set to false are exported.

### Current Behavior
All products which has published set to true are exported.

**Comment by wizzy25** [comment]
@VasumathiJayakumar Can you give the exact predicate you used (full predicate)? As well as context? It could well be an invalid predicate. See #171 for more details

**Comment by junajan** [comment]
@wizzy25 - yeah .. we found out that there are two issues
 1. there is missing that `where=` prefix
 2. and this tools is loading data from `products-projection` so no need for that `masterData` part

It is a little bit misleading that the label says "where predicate" and the attached link also leads to predicates documentation without any note how the propper query should look like.

Therefore I propose to add some better documentation to this tool or to split the query to `where` predicate and `staged` flag (so users would fill only predicate there and they would check the checkbox if they want staged true/false)

**Comment by wizzy25** [comment]
@junajan An issue will be created in impex, to update the `specify where predicate` line, and possibly add examples
