### ISSUE TITLE
Remove support for `customWherePredicate`

### ISSUE THREAD

**Issue by adnasa** [sphereio/sphere-node-product-csv-sync#176]
I want to suggest that we remove the support for `customWherePredicate`

My reasoning for this are:

1. This is only used in `export.spec.coffee` as far as I can tell
2. This is not available as a CLI parameter
3. This eliminates the risk of error proned mapping of the where-predicate when it is constructed before the request

WDYT @wizzy25 @hisabimbola ?
cc @tdeekens 

---

Marking this as `maintenance`, since this is an intermediate re-factor

**Comment by Oehmi** [comment]
Will be closed as there is no support for it atm, it has already been resolved.
