### ISSUE TITLE
Impex product-import template header with spaces 

### ISSUE THREAD

**Issue by abernhar** [sphereio/sphere-node-product-csv-sync#178]
### Description

If you want to import products and at the template header has a space, the import does not work.

Example 

false:
productType,sku,variantid ,name.de....

correct:
productType,sku,variantid,name.de....

### Expected Behavior
The space should be ignored and the import should work

### Current Behavior
The space is not ignored and the import did not work

**Comment by hisabimbola** [comment]
Hello @abernhar,

Thanks for reporting, this is not a bug but it's a good enhancement that can be added to the tool.
