### ISSUE TITLE
Where query for status (delete) changes

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-node-product-csv-sync#181]
### (wished) Behavior
where parameter is applied on product status changes, too 

### Current Behavior
not applied and also documented that way.   But it's needed. 

### Context
Trying to delete a certain subset of the products.   No CLI does the job, so sitting in front of MC and doing batch delete of 20 each because MC crashes on more than that. 

### Possible Solution
respect the where parameter on all status change operations, too.

**Comment by hisabimbola** [comment]
Do you mean *delete* using the [product state command](https://github.com/sphereio/sphere-node-product-csv-sync#product-state)?

**Comment by nkuehn** [comment]
well, yes. If I say delete I mean deleting.  And yes, there is no other way but the product state command to do bulk deletes.

**Comment by hisabimbola** [comment]
Okay, thanks for clarifying.

We will prioritize and see how we can improve the tool.

**Comment by nkuehn** [comment]
it's not urgent. Was a one-time thing.

**Comment by Oehmi** [comment]
(!) update - product STATUS changes (published/unpublished/delete) are meant here, not states.

**Comment by nkuehn** [comment]
See above.  It was a one-time issue and if nobody else had it you have to decide for yourself whether this is a use case for more people.
