### ISSUE TITLE
Product Export: support searchKeywords

### ISSUE THREAD

**Issue by Oehmi** [sphereio/sphere-node-product-csv-sync#184]
### Description
It's possible to define searchKeywords for a product, either standard or with whitespace. Whitespace SearchKeywords are displayed in Merchant Center wit a "|" , but the Product Export does not support the difference between standard and Whitespace. The keywords simply separated by ";" and IMPEX only seems to support standard searchKeywords. 

### Expected Behavior
Product import and export should support searchKeywords with whitespace and also differentiate between standard & whitespace keywords. 

### Current Behavior
At the moment, it seems that only standard searchKeywords are exported, and that IMPEX does not support whitespace searchKeywords in the product export. 

### Support Reference
SUPPORT-1414

**Comment by Oehmi** [comment]
FYI: This issue will be done in new product parser

**Comment by wizzy25** [comment]
This issue has been resolved in the [new parser](https://github.com/commercetools/nodejs/tree/master/packages/product-json-to-csv) and will not be implemented here
