### ISSUE TITLE
Product Import: Variant key of a new variant of an existing product is not stored

### ISSUE THREAD

**Issue by VasumathiJayakumar** [sphereio/sphere-node-product-csv-sync#185]
### Description
When a new variant is added to an existing product, the variant key of that new variant is not saved on the product while importing. 

### Expected Behavior
variant key is saved on the new variant of the product

### Current Behavior
variant key is empty on the newly added variant

**Comment by wizzy25** [comment]
This issue has been fixed [here](https://github.com/sphereio/sphere-node-sdk/pull/244)
