### ISSUE TITLE
Support changeMasterVariant update action

### ISSUE THREAD

**Issue by VasumathiJayakumar** [sphereio/sphere-node-product-csv-sync#190]
### Description
The update action [changeMasterVariant](https://dev.commercetools.com/http-api-projects-products.html#change-master-variant) is not currently supported.

### Expected Behavior
Should be able to set any variant as masterVariant through CSV file.
 
### Current Behavior
It is currently not possible to set any variant as masterVariant now through CSV file or it is not specified how to do so.

### Context
It is not possible to set any variant as masterVariant now through CSV file.

**Comment by Oehmi** [comment]
@wizzy25  @junajan 
Brainstorming idea: first variant is always the master variant and can be changed

**Comment by Oehmi** [comment]
Update - New SDK would supports this update action, but has not been added yet.

**Comment by skyriakou** [comment]
@stmeissner is this still something we need? are there any customer requests that need this feature? Thanks!

**Comment by stmeissner** [comment]
@skyriakou I can't trace back where this request came from.

**Comment by skyriakou** [comment]
Since we have no active customer request for this feature we will close the issue.
