### ISSUE TITLE
Product Export: add createdAT & lastModifiedAT

### ISSUE THREAD

**Issue by Oehmi** [sphereio/sphere-node-product-csv-sync#196]
### Support reference number
none

### Description
For the Product Export without template, we would like to have the information about createdAt and lastModifiedAt for each product. 

### Context
After discussing with @wizzy25, it has to be evaluated first whether this will have impact on the product import as well, or if the new fields are ignored in the product import.

**Comment by wizzy25** [comment]
This feature has been implemented in the new [product parser](https://github.com/commercetools/nodejs/tree/master/packages/product-json-to-csv) and as a result will not be implemented here.
fyi @Oehmi
