### ISSUE TITLE
Corrupted zip file when exporting product

### ISSUE THREAD

**Issue by VasumathiJayakumar** [sphereio/sphere-node-product-csv-sync#203]
### Support reference number

came across when reproducing the scenario from the below ticket
https://jira.commercetools.com/browse/SUPPORT-2920

### Description
When there is a attribute in the same name as a keyword of our platform, for ex. "productType", then performing product export as a csv, outputs an corrupted zip file. On opening this zip file, it creates another file with extension .cpgz.

When performing the same product export to get an excel we get an error _**"There are duplicate header entries"**_

### Expected Behavior
Same error as we get when exporting as excel.

### Current Behavior
Corrupted zip file, which on opening creates file with extension .cpgz

**Comment by wizzy25** [comment]
As this is caused by a faulty data structure, there's not much that can be done from here
fyi @VasumathiJayakumar
