### ISSUE TITLE
Change misleading error message

### ISSUE THREAD

**Issue by stmeissner** [sphereio/sphere-node-product-csv-sync#210]
### Support reference number
SUPPORT-3170

### Description
Use product importer with following CSV file in which the name.en is just a '.'
[base_update.txt](https://github.com/sphereio/sphere-node-product-csv-sync/files/2045565/base_update.txt)

### Expected Behavior
IMPEX should tell in the error message that "name.en" is not valid.

### Current Behavior
IMPEX tells in the error message that a slug could not be generated.

> [ '[row undefined:slug] Can\'t generate valid slug out of \'\'!' ]

### Context
A partner was trying to import products, but could not find the root cause of the problem due to misleading error message.

**Comment by Babanila** [comment]
@stmeissner is the client trying to import .txt file or .csv file? We fixed a similar issue on staging environment, could you please check if you get the correct error there?

**Comment by Babanila** [comment]
@stmeissner the API accept the "." as a valid string, I suggest we take away the error to allow update, what do you think ?
see here in the docs [here](https://docs.commercetools.com/http-api-types.html#localizedstring)

**Comment by stmeissner** [comment]
@Babanila sorry for the delay, I would have agreed anyways 👍 
thanks for the fix.
