### ISSUE TITLE
Template subcommand does not accept project config via parameters

### ISSUE THREAD

**Issue by easybi-vv** [sphereio/sphere-node-product-csv-sync#245]
### Description
Module was installed via _npm install sphere-node-product-csv-sync_.
Running the template subcommand requires the project auth config to be given (project key, project client id, client secret), but they are never actually used.

### Expected Behavior
Running 
```
product-csv-sync template --projectKey <project-key> --clientId <client-id> --clientSecret <client-secret> --out <file>
```
generates a template file for export.

### Current Behavior
The error
```
Problems on getting client credentials from config files: Error: No project defined. Please enter a project key
```
is returned upon running the subcommand.

### Possible Solution
In src/coffee/export.coffee on line 322, @projectKey should also be passed to the getAll function. 

Additionally - thought this may be a peculiarity of my own sphere project - on line 324, just productTypes should only be assigned "result", not "result.body.results".

**Comment by wirtsi** [comment]
Can confirm, this seems to be a bug in the template export.

**Comment by skyriakou** [comment]
@easybi-vv thanks for your request, we will put this on our backlog. However, if it is urgent we recommend to do a pull request or to create a support request over our [official support channel](https://jira.commercetools.com/servicedesk/customer/portal/1). Thanks.
