### ISSUE TITLE
Product Import should also allows the usage of category key

### ISSUE THREAD

**Issue by skyriakou** [sphereio/sphere-node-product-csv-sync#247]
### Support reference number
https://jira.commercetools.com/browse/SUPPORT-5264

### Description
A helpful feature would be to allow the product-csv-sync tool to import product linking categories also by key.

Currently is possible to use: externalId, namedPath and name (in that order).

Extending this feature also by key would allow better usage of the tool and also make it consistent with the options in the export (IMPEX UI) where it is possible to choose the following options for categories: name, key, externalId, namedPath

Right now I have a use case where the PIM is able to create the same combination used in the keys but is not possible to import a product in this way without extra development.

**Comment by VineetKumarKushwaha** [comment]
The priorities will be like below:-
It will first check for **externalId**, then **namedPath**, then **name** and then  **key**
