### ISSUE TITLE
Error running product-csv-sync export

### ISSUE THREAD

**Issue by briantomkins** [sphereio/sphere-node-product-csv-sync#248]
### Support reference number
https://jira.commercetools.com/browse/SUPPORT-5384

### Description
running product-csv-sync export throws immediate error 
```js
Problems on getting client credentials from config files: TypeError: Cannot read property 'debug' of undefined
```

```js
product-csv-sync export --projectKey blt-nail --clientId os3KztGi5jry7Dz76A4GbaE4 --clientSecret XXX--language de --fillAllRows --out bltexport.csv —template template_all.csv
```

### Expected Behavior
normal export

### Current Behavior
no output just error

### Context
Unable to export product data

### Possible Solution
use product exporter (in small chunks)

**Comment by daern91** [comment]
Hi @briantomkins,

I see a small error in the command you run, namely, the last flag passed in.
`—template template_all.csv`

All flags requires double dashes, so could you please add another one? `--template template_all.csv`.

Full command is then 
`product-csv-sync export --projectKey blt-nail --clientId os3KztGi5jry7Dz76A4GbaE4 --clientSecret XXX--language de --fillAllRows --out bltexport.csv --template template_all.csv
`
and should work

**Comment by briantomkins** [comment]
product-csv-sync export --projectKey blt-nail --clientId os3KztGi5jry7Dz76A4GbaE4 --clientSecret XXX --language de --fillAllRows --out bltexport.csv -t template_all.csv
worked thanks
