### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by Tobi-mmt** [sphereio/sphere-node-product-csv-sync#284]
### Description
As a user of this package, I expect a changelog of the different releases. It would be also very nice if the release explains what changed exactly and why it is a breaking change. So I can modify my code to work with the new version. 
_(yes I can look in the commits, but that's not the way it should be from my point of view)_

I would also expect a description why the major version increases 2 numbers, skipping the version 3.0

### Expected Behavior
A changelog with all the breaking changes, features and/or bugfixes. Also a description why there is no version 3.0

### Current Behavior
Wrong 'latest release' label. No infos for 4.0
![Bildschirmfoto 2020-03-30 um 11 18 15](https://user-images.githubusercontent.com/14888529/77896178-2922a600-7278-11ea-933b-20fb52122ed7.png)

### Context
I don't know what breaks if I update to the new version 4.0 without digging into the codebase

### Possible Solution
Create a changelog while you make changes. Each feature is summerized into this file and will be published with the new release. E.g. https://github.com/olivierlacan/keep-a-changelog

**Comment by daern91** [comment]
cc @VineetKumarKushwaha, could you please add this to the release pages as described above? https://github.com/sphereio/sphere-node-product-csv-sync/releases

I looked at the commits and it seems like we bumped directly from 2.0.0 to 4.0.0. If this was a mistake please also document it so we don't confuse people.

**Comment by VineetKumarKushwaha** [comment]
@Tobi-mmt Thanks for letting us know. We have updated the change log and we want to let you know that we accidentally skipped the v3.0.0.

**Comment by VineetKumarKushwaha** [comment]
Updated the release notes and created https://github.com/sphereio/sphere-node-product-csv-sync/issues/285 issue to add this step under release section so that we should not miss again.
