### ISSUE TITLE
v4.1.1 throws error while installing in yarn workspaces

### ISSUE THREAD

**Issue by Tobi-mmt** [sphereio/sphere-node-product-csv-sync#294]
### Support reference number

none

### Description

Same like https://github.com/sphereio/sphere-stock-import/issues/103
I use yarn as my package manager and i have a monorepo and use yarn workspaces

The project structure looks like this:

```
--package.json
--yarn.lock
--subfolder1
  |--package.json
--subfolder2
  |--package.json
```
So all the subfolders have a package.json but the lock file is only in the root. That's how yarn organizes workspaces.
If I add the `sphere-node-product-csv-sync` package in **version 4.1.1** to the path `subfolder1/package.json` and run `yarn install` the following error occures on all enviroments (CI and locally): (version 4.1.0 works well)

```
yarn install
/usr/bin/yarn
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/runner/work/path/to/repo/node_modules/sphere-node-product-csv-sync: Command failed.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exit code: 1
Command: npx npm-force-resolutions
Arguments: 
Directory: /home/runner/work/path/to/repo/node_modules/sphere-node-product-csv-sync
Output:
npx: installed 5 in 2.142s
ENOENT: no such file or directory, open './package-lock.json'
```

### Expected Behavior

Should work the same way as the version 4.1.0 without throwing an error while installing

### Current Behavior

Throws error like written above.

### Context

I just want to update from 4.1.0 to 4.1.1. Does not work with this error.

### Possible Solution

Remove command `npx npm-force-resolutions` from preinstall script and maybe resolve the vulnerable dependencies directly in the `package-lock.json`?

**Comment by daern91** [comment]
Thanks again!

cc @VineetKumarKushwaha 

(caused by PR https://github.com/sphereio/sphere-node-product-csv-sync/pull/293)

**Comment by okkevdeijkGV** [comment]
I can confirm that this issue also occurs when trying to use the library globally with NPM. Would be great if this can be picked up soon.

**Comment by VineetKumarKushwaha** [comment]
Released new patch version and verified by installing globaly with npm and yarn both.
@Tobi-mmt Please reopen if you still get error after updating to the latest.
