### ISSUE TITLE
Support reference type attribute

### ISSUE THREAD

**Issue by mmoelli** [sphereio/sphere-node-product-csv-sync#54]
I would like to have the possibilities to import, update and export product attribute which are using the new reference type. As the typeId is set in the product type we just the id of the refering resource.

simple reference attribute
```
refProduct
900dcd60-344c-11e4-8c21-0800200c9a66
```

set of reference attribute
```
setRefProduct
900dcd60-344c-11e4-8c21-0800200c9a66;c189a620-344c-11e4-8c21-0800200c9a66;cdbe5800-344c-11e4-8c21-0800200c9a66
```

**Comment by mmoelli** [comment]
@hajoeichler This feature is now required by the team. Any chance we can incorporate that?

**Comment by hajoeichler** [comment]
single product references work now. Anything else necessary for the MVP?

**Comment by mmoelli** [comment]
Nope. Not for now
