### ISSUE TITLE
REGEX_PRICE doens't accept prices with dashes in its channel

### ISSUE THREAD

**Issue by Sikian** [sphereio/sphere-node-product-csv-sync#77]
I came across this issue by chance, but it seems that due to the fact that the channel is being matched with this regex `(#(\w+)|)` it will not match channels containing a dash `-` (f.e. test-channel will not be matched). 

This is an issue due to the fact that Sphere's API allows creating channels with dashes in its key.

Thanks!

**Comment by hajoeichler** [comment]
@Sikian thx for pointing me at this tighten constraint. According to http://dev.sphere.io/http-api-projects-channels.html#channel we have to expect "any arbitrary string".
So what about `(#(.+)|)`?

**Comment by Sikian** [comment]
I'm afraid that might match `;` as well (unless it's being splitted before, which I haven't had the chance to check). If it's already being splitted, that would definitely work.

Small note: It seems like the string won't accept `\` either.

**Comment by hajoeichler** [comment]
Yes, the cell content is already split by `;`.
Just recognised the same constraint for customer groups too. Will adapt also.

**Comment by Sikian** [comment]
I was also considering that "arbitrary string" also includes spaces, which doesn't make much sense for keys.

**Comment by hajoeichler** [comment]
@Sikian you are right and we will reconsider that and might change it in the API.
Just checked
CustomerGroup:
```
{
  "groupName": "some with spaces"
}
```
results in:
```
{
  "id": "3627b65f-0a08-4d18-a26c-ff7f0601cd14",
  "version": 1,
  "name": "some with spaces",
  "createdAt": "2015-07-07T05:07:15.424Z",
  "lastModifiedAt": "2015-07-07T05:07:15.424Z"
}
```

and channels:
```
{
  "key": "some with s p a c e s"
}
```
is also valid:
```
{
  "id": "762fa3c1-2b2e-4b3a-bdb7-6edb80425209",
  "key": "some with s p a c e s",
  "version": 1,
  "roles": [
    "InventorySupply"
  ],
  "createdAt": "2015-07-07T05:09:26.348Z",
  "lastModifiedAt": "2015-07-07T05:09:26.348Z"
}
```

**Comment by Sikian** [comment]
Thanks for double checking!

I'd suggest /[a-z][A-Z][0-9]-_/ or even /[a-z][0-9]/ as I'm not sure if caps is a good idea in keys. Please let me know what's the final decision!

Thanks

**Comment by hajoeichler** [comment]
@Sikian I am with you that the best would to be more restrictive from the API level - eg. `/^[a-z0-9-_]+$/`.
But my current adjustments do actually fit to the current API constraints. So I would keep them for now.
