### ISSUE TITLE
Query for productType in csv export not working properly

### ISSUE THREAD

**Issue by CT-Szilvia** [sphereio/sphere-node-product-csv-sync#94]
Hi all, 

if I try to export products with a query  for the productType "product" with id=c090421b-207b-4c24-b3da-2b978279746d with following command:
1st try: 
./bin/product-csv-sync export --projectKey "xxx" --clientId "xxx" --clientSecret "xxx" --queryString 'where=productType(id="c090421b-207b-4c24-b3da-2b978279746d")' --fillAllRows  --template "template.csv" --out product.csv

2nd try: 
./bin/product-csv-sync export --projectKey "xxx" --clientId "xxx" --clientSecret "xxx" --queryString 'where=productType(id%3D%22c090421b-207b-4c24-b3da-2b978279746d%22)' --queryEncoded --fillAllRows  --template "template.csv" --out product.csv

I get following message: 
Fetched 2 product type(s).
Fetched 20 product(s).
Fetched 20 product(s).
Fetched 20 product(s).
Fetched 20 product(s).
Fetched 19 product(s).
Export done.
So it exports both productTypes. Could you please take a look? 

Thanks, 
Szilvia

**Comment by hajoeichler** [comment]
@CT-Szilvia This issue is solved, right?

**Comment by sebbulon** [comment]
@hajoeichler it's not unfortunately...

**Comment by hajoeichler** [comment]
Fix was done in node SDK https://github.com/sphereio/sphere-node-sdk/commit/d0e3d6e4b61c0113dbda5434b649a2b13e96d26a

**Comment by sebbulon** [comment]
hmm let me check..

**Comment by sebbulon** [comment]
it seems like the change was "merged out" of the node SDK - I will fix it

**Comment by PhilippSpo** [comment]
@sebbulon any updates on this? Should I take over?

**Comment by CT-Szilvia** [comment]
Hi @PhilippSpo & @hajoeichler last week I could use the query. So I think yes, but maybe @sebbulon can tell you more?

**Comment by sebbulon** [comment]
@PhilippSpo yes please take this over.  thanks

**Comment by PhilippSpo** [comment]
OK this one is interesting. The filter is applied on the list of products, but not on the initial loading of product types. So all existing product types get loaded at first and afterwards all the products get filtered. This "works" but is obviously not optimal..

**Comment by hajoeichler** [comment]
Yes, we only use the query for the products endpoint.
To filter the product type on both endpoints we need to change a lot and loose the general idea to allow to use the query of the products endpoint.

**Comment by stmeissner** [comment]
this is not working for me:
`--queryString 'productType.id:"<product-type-id>"'`
with or without `--queryType 'search'`

**Comment by hajoeichler** [comment]
Please use productType(id = "123")

**Comment by stmeissner** [comment]
@hajoeichler works
